"""Generated documentation: docs/questions.md, docs/ownership.csv, docs/post-event-lessons.md,
crosswalk/wa-bp-map.csv, and the generated blocks inside MIGRATION.md and docs/scoring.md.

Whole files are owned by the generator. MIGRATION.md and docs/scoring.md are written by people; the generator
replaces only the text between its marker lines and never creates those files or adds markers:

    <!-- BEGIN GENERATED: migration-mapping (python3 -m tools.orrlens docs; do not edit) -->
    <!-- END GENERATED: migration-mapping -->

    <!-- BEGIN GENERATED: scoring-deviations (python3 -m tools.orrlens docs; do not edit) -->
    <!-- END GENERATED: scoring-deviations -->
"""

from __future__ import annotations

import csv
import io
import re
from pathlib import Path

from . import config as C
from .registry import dispositions
from .render import t

GENERATED_NOTE = "Generated by `python3 -m tools.orrlens docs` from `lens-src/`. Do not edit by hand."
BLOCKS = {
    "MIGRATION.md": "migration-mapping",
    "docs/scoring.md": "scoring-deviations",
}
# Marker spellings accepted besides the canonical "BEGIN GENERATED: <name>" form
MARKER_ALIASES = {
    "migration-mapping": ["migration-mapping", "MAPPING"],
    "scoring-deviations": ["scoring-deviations", "DEVIATIONS"],
}
MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
RISK_WORD = {"HIGH": "High", "MEDIUM": "Medium"}


def begin_marker(name: str) -> str:
    return f"<!-- BEGIN GENERATED: {name} (python3 -m tools.orrlens docs; do not edit) -->"


def end_marker(name: str) -> str:
    return f"<!-- END GENERATED: {name} -->"


def _cell(v) -> str:
    return t(v).replace("|", "\\|")


def _csv(rows, header) -> str:
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(header)
    w.writerows(rows)
    return buf.getvalue()


def _tier_label(tier: str) -> str:
    return {"scope": "scope exit", "core": "core", "sec": "secondary"}.get(tier, tier.replace("alt:", "alternative "))


# ---------------------------------------------------------------------------
# docs/questions.md
# ---------------------------------------------------------------------------

def questions_md(lenses, rendered: dict) -> str:
    out = ["# The ORR lens family, question by question", "", GENERATED_NOTE,
           "The JSON files in `dist/` are generated from the same sources.", ""]
    out += ["Risk rules are evaluated top to bottom and the first true condition sets the risk. Tiers: a scope exit "
            "scores No risk on its own; core statements are needed to avoid High; one statement of each "
            "alternative group is needed to avoid High; secondary statements are needed only for No risk. "
            "\"None of these\" (`none_no`) appears only in the guard `&& !none_no` on the No risk and Medium "
            "rules (sandbox gate G1), so selecting it, alone or with other choices, scores the question's "
            "maximum risk.", ""]
    for lens in lenses:
        doc = rendered.get(lens.key)
        if not doc:
            continue
        src = {q["id"]: q for q in lens.valid_questions}
        n_q = sum(len(p["questions"]) for p in doc["pillars"])
        n_s = sum(len(q["choices"]) - 1 for p in doc["pillars"] for q in p["questions"])
        n_core = sum(1 for q in src.values() if q.get("core_path"))
        out += [f"## {doc['name']} {lens.version}", "",
                f"{n_q} questions, {n_s} scored statements"
                + (f", {n_core} on the core path." if n_core else "."), ""]
        out += ["| Pillar | Questions |", "|---|---|"]
        for p in doc["pillars"]:
            out.append(f"| {_cell(p['name'])} (`{p['id']}`) | {len(p['questions'])} |")
        out.append("")
        for p in doc["pillars"]:
            out += [f"### {p['name']}", ""]
            for q in p["questions"]:
                s = src[q["id"]]
                out += [f"#### `{q['id']}`: {t(q['title'])}", "", "| | |", "|---|---|",
                        f"| Maximum risk | {RISK_WORD[s['max_risk']]} |",
                        f"| Category | {_cell(s['category'])} |",
                        f"| Core path | {'Yes' if s.get('core_path') else 'No'} |"]
                lineage = ", ".join(f"`{x}`" for x in s.get("lineage") or []) or "new topic"
                out += [f"| v{C.V1_CURRENT} lineage | {lineage} |", "", t(q["description"]), ""]
                out += ["| Choice | Tier | Statement |", "|---|---|---|"]
                tiers = {st["id"]: st["tier"] for st in s["statements"]}
                for c in q["choices"]:
                    tier = _tier_label(tiers[c["id"]]) if c["id"] in tiers else "none"
                    out.append(f"| `{c['id']}` | {tier} | {_cell(c['title'])} |")
                out += ["", "Risk rules:", ""]
                for i, r in enumerate(q["riskRules"], 1):
                    out.append(f"{i}. `{r['risk']}`: `{r['condition']}`")
                out += ["", "Statement detail:", ""]
                for c in q["choices"]:
                    if c["id"] not in tiers:
                        continue
                    hc = (c.get("helpfulResource") or {}).get("displayText")
                    ic = (c.get("improvementPlan") or {}).get("displayText")
                    if not hc and not ic:
                        continue
                    out += ["<details>", f"<summary><code>{c['id']}</code>: {_cell(c['title'])}</summary>", ""]
                    if hc:
                        out += [_cell(hc), ""]
                    if ic:
                        out += [f"Improvement plan: {_cell(ic)}", ""]
                    out += ["</details>", ""]
                out += ["Sources:", ""]
                hr = q.get("helpfulResource") or {}
                if hr.get("url"):
                    out.append(f"- Question: {_cell(hr.get('displayText'))} <{hr['url']}>")
                for c in q["choices"]:
                    urls = []
                    for k, label in (("helpfulResource", "helpful"), ("improvementPlan", "improvement")):
                        u = (c.get(k) or {}).get("url")
                        if u:
                            urls.append(f"{label} <{u}>")
                    for a in c.get("additionalResources", []):
                        label = "additional helpful" if a["type"] == "HELPFUL_RESOURCE" else "additional improvement"
                        for item in a["content"]:
                            if item.get("url"):
                                urls.append(f"{label} <{item['url']}>")
                    if urls:
                        out.append(f"- `{c['id']}`: " + "; ".join(urls))
                out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# docs/ownership.csv, crosswalk/wa-bp-map.csv, docs/post-event-lessons.md
# ---------------------------------------------------------------------------

def ownership_csv(lenses) -> str:
    """One row per statement. orr_lens (the lens key: core, event, genai) is the last column, so readers of the
    original four columns are unaffected."""
    rows = []
    for lens in lenses:
        for q in lens.valid_questions:
            absorbed = ";".join(q.get("lineage") or [])
            for s in q["statements"]:
                rows.append([s["concept"], q["id"], s["id"], absorbed, lens.key])
    return _csv(rows, ["concept", "owner_question", "statement", "v1_ids_absorbed", "orr_lens"])


def wa_bp_csv(lenses, wa_bps) -> str:
    """One row per statement with a wa_bp. framework_version is set for Framework practices only; bp_source names
    the Framework or the AI lens that publishes the practice and bp_source_version its version (the Framework
    version, or the lens publication date). New columns are appended after the original five."""
    entries = wa_bps.entries if wa_bps is not None else {}
    default_fv = (wa_bps.meta.get("framework_version") if wa_bps is not None else "") or ""
    rows = []
    for lens in lenses:
        for q in lens.valid_questions:
            for s in q["statements"]:
                bp = s.get("wa_bp")
                if not bp:
                    continue
                e = entries.get(bp, {})
                src = e.get("lens") or C.wa_bp_source(bp) or C.WA_FRAMEWORK
                fw = src == C.WA_FRAMEWORK
                fv = (e.get("framework_version") or default_fv) if fw else ""
                rows.append([s["id"], bp, e.get("title", ""), e.get("url", ""), fv,
                             C.WA_BP_SOURCES.get(src, {}).get("name", src),
                             fv if fw else e.get("lens_version", ""), lens.key])
    return _csv(rows, ["statement_id", "wa_bp", "bp_title", "bp_url", "framework_version", "bp_source",
                       "bp_source_version", "orr_lens"])


def _sentence(text: str) -> str:
    """Capitalize the first letter, leaving an identifier or an acronym that already starts upper case alone."""
    t2 = str(text).strip()
    if not t2 or not t2[0].isalpha() or t2.split()[0].strip(",.").isupper() or "_" in t2.split()[0]:
        return t2
    return t2[0].upper() + t2[1:]


def _month_key(m: str):
    parts = str(m).split()
    try:
        return (int(parts[1]), MONTHS.index(parts[0]))
    except (IndexError, ValueError):
        return (9999, 0)


def post_event_md(lenses) -> str:
    groups: dict = {}
    for lens in lenses:
        for q in lens.valid_questions:
            pes = q.get("pes_lesson")
            if not pes:
                continue
            key = (str(pes["month"]), str(pes["url"]))
            groups.setdefault(key, []).append((t(pes["lesson"]), q["id"], lens.key))
    out = ["# Related AWS Post-Event Summaries", "", GENERATED_NOTE, "",
           "Each lesson is a one-sentence customer design takeaway, written from the public summary. AWS keeps "
           "Post-Event Summaries available for a minimum of 5 years, and the weekly link check covers these links.",
           ""]
    if not groups:
        out.append("No Post-Event Summary lessons are recorded yet.")
        return "\n".join(out) + "\n"
    out += ["| Date | Post-Event Summary | Questions | Lesson |", "|---|---|---|---|"]
    for (month, url), items in sorted(groups.items(), key=lambda kv: (_month_key(kv[0][0]), kv[0][1])):
        by_lesson: dict = {}
        for lesson, qid, lens_key in items:
            by_lesson.setdefault(lesson, []).append(f"`{qid}`" + ("" if lens_key == "core" else f" ({lens_key})"))
        first = True
        for lesson, qs in by_lesson.items():
            date_cell = month if first else ""
            url_cell = f"<{url}>" if first else ""
            first = False
            out.append(f"| {date_cell} | {url_cell} | {', '.join(qs)} | {_cell(_sentence(lesson))} |")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Generated blocks
# ---------------------------------------------------------------------------

def migration_block(rows) -> str:
    out = [f"| v{C.V1_CURRENT} question | v{C.V1_CURRENT} title | Disposition | v2 question(s) |", "|---|---|---|---|"]
    for v1id, title, disp, targets in rows:
        v2 = "; ".join(f"`{qid}` {_cell(title2)}" for qid, title2 in targets) or "(not mapped yet)"
        out.append(f"| `{v1id}` | {_cell(title)} | {disp} | {v2} |")
    counts: dict = {}
    for r in rows:
        k = "keep" if r[2].startswith("keep") else r[2]
        counts[k] = counts.get(k, 0) + 1
    summary = ", ".join(f"{k} {v}" for k, v in sorted(counts.items()))
    out += ["", f"{len(rows)} v{C.V1_CURRENT} questions: {summary}. Dispositions are computed from the `lineage` of each "
            "v2 question: keep means the question id is unchanged (its choice ids are all new); merge means the "
            "content moved into one v2 question; split means it moved into several."]
    return "\n".join(out)


def scoring_block(lenses) -> str:
    rows = []
    for lens in lenses:
        for q in lens.valid_questions:
            for s in q["statements"]:
                basis = t(s.get("severity_basis"))
                if basis.startswith("deviation:"):
                    rows.append(f"| `{q['id']}` | `{s['id']}` {_cell(s['title'])} | {_cell(basis[len('deviation:'):].strip())} |")
    if not rows:
        return "No statement records a `deviation:` severity basis yet."
    return "\n".join(["| Question | Statement | Rationale |", "|---|---|---|"] + rows)


def apply_block(text: str, name: str, content: str):
    """Replace the content between the markers for `name`. Returns None when the markers are absent.

    Accepted markers: `<!-- BEGIN GENERATED: <name> ... -->` or `<!-- BEGIN GENERATED <ALIAS> -->`, and the matching
    END marker (see MARKER_ALIASES).
    """
    alts = "|".join(re.escape(a) for a in MARKER_ALIASES.get(name, [name]))
    b = re.search(r"<!--\s*BEGIN GENERATED:?\s+(?:" + alts + r")\b[^>]*-->[ \t]*\n?", text)
    if not b:
        return None
    e = re.compile(r"<!--\s*END GENERATED:?\s+(?:" + alts + r")\s*-->").search(text, b.end())
    if not e:
        return None
    return text[:b.end()].rstrip("\n") + "\n" + content.strip("\n") + "\n" + text[e.start():]


# ---------------------------------------------------------------------------
# All generated docs
# ---------------------------------------------------------------------------

def generate(root: Path, lenses, rendered: dict, wa_bps) -> tuple[dict, dict]:
    """Return (files, blocks): files maps a path to its full content; blocks maps a path to (name, content)."""
    files = {
        "docs/questions.md": questions_md(lenses, rendered),
        "docs/ownership.csv": ownership_csv(lenses),
        "docs/post-event-lessons.md": post_event_md(lenses),
        "crosswalk/wa-bp-map.csv": wa_bp_csv(lenses, wa_bps),
    }
    blocks = {
        "MIGRATION.md": (BLOCKS["MIGRATION.md"], migration_block(dispositions(root, lenses))),
        "docs/scoring.md": (BLOCKS["docs/scoring.md"], scoring_block(lenses)),
    }
    return files, blocks


def write(root: Path, lenses, rendered: dict, wa_bps) -> list:
    """Write the generated docs. Returns human-readable notes (written, unchanged, skipped)."""
    files, blocks = generate(root, lenses, rendered, wa_bps)
    notes = []
    for rel, content in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != content:
            path.write_text(content, encoding="utf-8")
            notes.append(f"wrote {rel}")
        else:
            notes.append(f"unchanged {rel}")
    for rel, (name, content) in blocks.items():
        path = root / rel
        if not path.exists():
            notes.append(f"skipped {rel}: file does not exist yet (add the {name} markers to it)")
            continue
        old = path.read_text(encoding="utf-8")
        new = apply_block(old, name, content)
        if new is None:
            notes.append(f"skipped {rel}: no {name} markers (add {begin_marker(name)} and {end_marker(name)})")
        elif new != old:
            path.write_text(new, encoding="utf-8")
            notes.append(f"updated the {name} block in {rel}")
        else:
            notes.append(f"unchanged {rel} ({name} block)")
    return notes


def check_fresh(root: Path, lenses, rendered: dict, wa_bps) -> list:
    files, blocks = generate(root, lenses, rendered, wa_bps)
    fails = []
    for rel, content in files.items():
        path = root / rel
        if not path.exists():
            fails.append(f"{rel} is missing; run `python3 -m tools.orrlens docs`")
        elif path.read_text(encoding="utf-8") != content:
            fails.append(f"{rel} is stale; run `python3 -m tools.orrlens docs`")
    for rel, (name, content) in blocks.items():
        path = root / rel
        if not path.exists():
            fails.append(f"{rel} does not exist, so its generated {name} block is missing")
            continue
        old = path.read_text(encoding="utf-8")
        new = apply_block(old, name, content)
        if new is None:
            fails.append(f"{rel} has no {name} markers ({begin_marker(name)} ... {end_marker(name)})")
        elif new != old:
            fails.append(f"{rel}: the {name} block is stale; run `python3 -m tools.orrlens docs`")
    return fails

