"""ID registry (ids.yaml): seeding from the published v1 files, deterministic updates, and the ids check.

Registry rules: IDs are never reused and never change meaning; history fields are never
rewritten. History is the part of the registry that a released version fixed:
- every v1.3.x id: its introduced version and, if it left the lens before 1.3.6, its retired version are computed
  from the published v1 files, which never change;
- an entry whose `retired` is an earlier version than its lens's current version is frozen;
- an entry introduced in its lens's current, unreleased version disappears again if its source disappears
  (it was never published), and an entry retired "in" the current version is provisional until release.
The question ids in config.PERMANENT_RETIREMENTS are always retired.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

from . import config as C

HEADER = """\
# ID registry for the ORR lens family (see tools/orrlens/README.md, "ID registry rules").
# Generated by: python3 -m tools.orrlens ids update   (do not edit by hand)
# Every pillar, question and choice id ever published, with its status and the version that introduced or retired
# it. Choice ids are keyed "<question_id>/<choice_id>" because v1 choice ids repeat across questions.
# IDs are never reused and never change meaning. Status: active | retired | reserved.
"""


def vkey(v: str):
    """Sort key for versions such as 1.3.2, 2.0.0 and 2.0.0rc1."""
    m = re.match(r"^(\d+)\.(\d+)\.(\d+)(?:rc(\d+))?$", str(v))
    if not m:
        return (999, 0, 0, 0)
    a, b, c, rc = m.groups()
    return (int(a), int(b), int(c), int(rc) if rc is not None else 10**6)


# ---------------------------------------------------------------------------
# v1 history
# ---------------------------------------------------------------------------

def load_v1(root: Path):
    """Return {version: parsed JSON} for every published v1.3.x file, in version order."""
    out = {}
    files = sorted((root / C.V1_DIR).glob(C.V1_GLOB))
    for f in files:
        m = re.search(r"orr-v(\d+\.\d+\.\d+)-PUBLISHED\.json$", f.name)
        if m:
            out[m.group(1)] = json.loads(f.read_text(encoding="utf-8"))
    return dict(sorted(out.items(), key=lambda kv: vkey(kv[0])))


def v1_history(v1: dict):
    """Return {kind: {key: (first_version, last_version)}} for pillars, questions and choices."""
    hist = {"pillars": {}, "questions": {}, "choices": {}}

    def note(kind, key, ver):
        first, last = hist[kind].get(key, (ver, ver))
        hist[kind][key] = (min(first, ver, key=vkey), max(last, ver, key=vkey))

    for ver, doc in v1.items():
        for p in doc.get("pillars", []):
            note("pillars", p["id"], ver)
            for q in p.get("questions", []):
                note("questions", q["id"], ver)
                for c in q.get("choices", []):
                    note("choices", f"{q['id']}/{c['id']}", ver)
    return hist


def v1_question_titles(v1: dict, version: str = C.V1_CURRENT) -> dict:
    doc = v1.get(version) or {}
    return {q["id"]: q["title"] for p in doc.get("pillars", []) for q in p.get("questions", [])}


def v1_choice_ids_by_question(v1: dict) -> dict:
    out: dict = {}
    for doc in v1.values():
        for p in doc.get("pillars", []):
            for q in p.get("questions", []):
                out.setdefault(q["id"], set()).update(c["id"] for c in q.get("choices", []))
    return out


# ---------------------------------------------------------------------------
# Current sources
# ---------------------------------------------------------------------------

def current_ids(lenses):
    """Return {kind: {key: lens_key}} for the ids in the current lens sources (questions that parse)."""
    cur = {"pillars": {}, "questions": {}, "choices": {}}
    for lens in lenses:
        for p in lens.meta.get("pillars") or []:
            if isinstance(p, dict) and p.get("id"):
                cur["pillars"].setdefault(str(p["id"]), lens.key)
        for q in lens.questions:
            qid = q.get("id")
            if not isinstance(qid, str) or not qid:
                continue
            cur["questions"].setdefault(qid, lens.key)
            for s in q.get("statements") or []:
                if isinstance(s, dict) and isinstance(s.get("id"), str):
                    cur["choices"].setdefault(f"{qid}/{s['id']}", lens.key)
            cur["choices"].setdefault(f"{qid}/{C.NONE_ID}", lens.key)
    return cur


# ---------------------------------------------------------------------------
# Registry computation
# ---------------------------------------------------------------------------

def load_registry(root: Path):
    path = root / C.IDS_FILE
    if not path.exists():
        return None
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return data if isinstance(data, dict) else {}


def compute_registry(root: Path, lenses, existing: dict | None = None) -> dict:
    """Recompute the registry deterministically from the v1 files, the lens sources and the existing history."""
    existing = existing or {}
    v1 = load_v1(root)
    v1_versions = list(v1)
    hist = v1_history(v1)
    cur = current_ids(lenses)
    lens_versions = {lens.key: lens.version for lens in lenses}
    core_version = lens_versions.get("core", "2.0.0")

    def next_after(ver):
        later = [v for v in v1_versions if vkey(v) > vkey(ver)]
        return later[0] if later else core_version

    reg = {"schema": "orrlens/ids/1",
           "lenses": {k: {"current_version": v} for k, v in sorted(lens_versions.items())},
           "v1_versions": v1_versions,
           "reserved": {"prefixes": {C.RESERVED_PREFIX: {"status": "reserved",
                                                          "note": "organization overlays (x_<org>_)"}}},
           "pillars": {}, "questions": {}, "choices": {}}

    for kind in ("pillars", "questions", "choices"):
        old = existing.get(kind) or {}
        keys = set(hist[kind]) | set(cur[kind]) | set(old)
        for key in sorted(keys):
            o = old.get(key) if isinstance(old.get(key), dict) else {}
            in_cur = key in cur[kind]
            lens_key = cur[kind].get(key) or o.get("lens") or "core"
            lens_ver = lens_versions.get(lens_key, core_version)
            entry = {"lens": lens_key}
            if key in hist[kind]:
                first, last = hist[kind][key]
                entry["introduced"] = first
                computed_retired = None if in_cur else next_after(last)
            else:
                entry["introduced"] = str(o.get("introduced") or lens_ver)
                computed_retired = None
                if not in_cur:
                    if vkey(entry["introduced"]) >= vkey(lens_ver):
                        continue        # never published: drop it
                    computed_retired = lens_ver
            old_retired = o.get("retired")
            frozen = old_retired is not None and vkey(str(old_retired)) < vkey(lens_ver)
            qid = key.split("/")[0]
            if kind == "questions" and key in C.PERMANENT_RETIREMENTS:
                entry["status"], entry["retired"] = "retired", C.PERMANENT_RETIREMENTS[key]
            elif frozen:
                entry["status"], entry["retired"] = "retired", str(old_retired)
            elif key in hist[kind] and not in_cur:
                entry["status"], entry["retired"] = "retired", computed_retired
            elif key in hist[kind] and vkey(hist[kind][key][1]) < vkey(C.V1_CURRENT):
                # left the lens before v1.3.6 (history), so a current use is a reuse
                entry["status"], entry["retired"] = "retired", next_after(hist[kind][key][1])
            elif in_cur:
                entry["status"] = "active"
            else:
                entry["status"], entry["retired"] = "retired", computed_retired
            if kind == "choices" and qid in C.PERMANENT_RETIREMENTS and entry["status"] == "active":
                entry["status"], entry["retired"] = "retired", C.PERMANENT_RETIREMENTS[qid]
            reg[kind][key] = entry
    return reg


def dump_registry(reg: dict) -> str:
    """Deterministic YAML: one flow mapping per id, keys sorted."""
    def q(v):
        return json.dumps(str(v))

    def flow(e):
        order = ["lens", "status", "introduced", "retired", "note"]
        parts = [f"{k}: {q(e[k]) if k in ('introduced', 'retired', 'note') else e[k]}" for k in order if k in e]
        return "{" + ", ".join(parts) + "}"

    lines = [HEADER.rstrip("\n"), f"schema: {reg['schema']}", "lenses:"]
    for k, v in reg["lenses"].items():
        lines.append(f"  {k}: {{current_version: {q(v['current_version'])}}}")
    lines.append("v1_versions: [" + ", ".join(q(v) for v in reg["v1_versions"]) + "]")
    lines.append("reserved:")
    lines.append("  prefixes:")
    for k, v in reg["reserved"]["prefixes"].items():
        lines.append(f"    {k}: {flow(v)}")
    special = {"y", "n", "yes", "no", "on", "off", "true", "false", "null"}
    for kind in ("pillars", "questions", "choices"):
        lines.append(f"{kind}:")
        if not reg[kind]:
            lines[-1] += " {}"
        for k, v in reg[kind].items():
            key = q(k) if ("/" in k or k.lower() in special or not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", k)) else k
            lines.append(f"  {key}: {flow(v)}")
    return "\n".join(lines) + "\n"


def update(root: Path, lenses) -> tuple[str, bool]:
    """Regenerate ids.yaml. Returns (text, changed)."""
    existing = load_registry(root)
    text = dump_registry(compute_registry(root, lenses, existing))
    path = root / C.IDS_FILE
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old != text:
        path.write_text(text, encoding="utf-8")
    return text, old != text


# ---------------------------------------------------------------------------
# The ids check
# ---------------------------------------------------------------------------

def check_ids(root: Path, lenses, overlays_allowed: bool = False) -> list:
    fails = []
    existing = load_registry(root)
    v1 = load_v1(root)
    if C.V1_CURRENT not in v1:
        return [f"{C.V1_DIR}/orr-v{C.V1_CURRENT}-PUBLISHED.json is missing"]
    reg = compute_registry(root, lenses, existing)
    if existing is None:
        fails.append(f"{C.IDS_FILE} does not exist; run `python3 -m tools.orrlens ids update`")
    elif (root / C.IDS_FILE).read_text(encoding="utf-8") != dump_registry(reg):
        fails.append(f"{C.IDS_FILE} is out of date; run `python3 -m tools.orrlens ids update` and review the diff")

    v136 = v1_question_titles(v1)
    v1_choices = v1_choice_ids_by_question(v1)
    cur = current_ids(lenses)

    # No reuse of retired ids
    for kind in ("pillars", "questions", "choices"):
        for key in cur[kind]:
            e = reg[kind].get(key, {})
            if e.get("status") == "retired":
                fails.append(f"{kind[:-1]} id {key} was retired in {e.get('retired')} and cannot be reused")

    # Question ids are unique across lenses
    seen: dict = {}
    for lens in lenses:
        for q in lens.questions:
            qid = q.get("id")
            if qid in seen and seen[qid] != lens.key:
                fails.append(f"question id {qid} is used in lenses {seen[qid]} and {lens.key}")
            seen.setdefault(qid, lens.key)

    all_lineage: dict = {}
    for lens in lenses:
        prefixes: dict = {}
        for q in lens.questions:
            qid = str(q.get("id") or "")
            # Kept question ids must exist in v1.3.6; ids that existed only earlier are reuses
            if qid in v1_choices and qid not in v136:
                fails.append(f"{qid}: reuses a v1 question id that left the lens before v{C.V1_CURRENT}")
            if qid.startswith(C.RESERVED_PREFIX) and not overlays_allowed:
                fails.append(f"{qid}: the x_ prefix is reserved for organization overlays")
            sts = [s for s in q.get("statements") or [] if isinstance(s, dict)]
            sids = [str(s.get("id") or "") for s in sts]
            # No v2 choice id equals a v1 choice id of the same kept question
            if qid in v1_choices:
                clash = sorted(set(sids) & v1_choices[qid])
                if clash:
                    fails.append(f"{qid}: choice ids {clash} were used by v1 in the same question")
            # none_no everywhere; no other _no choice
            for sid in sids:
                if sid == C.NONE_ID or sid.endswith("_no"):
                    fails.append(f"{qid}/{sid}: only the generated None choice may be none_no or end in _no")
                if sid.startswith(C.RESERVED_PREFIX) and not overlays_allowed:
                    fails.append(f"{qid}/{sid}: the x_ prefix is reserved for organization overlays")
                if not re.match(r"^[a-z0-9_]{3,64}$", sid):
                    fails.append(f"{qid}/{sid}: choice id must be 3-64 characters of [a-z0-9_]")
            # Choice prefixes unique per question within a lens
            pre = q.get("choice_prefix")
            if pre:
                if pre in prefixes and prefixes[pre] != qid:
                    fails.append(f"{lens.key}: choice prefix {pre} is used by {prefixes[pre]} and {qid}")
                prefixes.setdefault(pre, qid)
                for sid in sids:
                    if not sid.startswith(pre):
                        fails.append(f"{qid}/{sid}: does not start with the question's choice prefix {pre}")
            for item in q.get("lineage") or []:
                all_lineage.setdefault(str(item), []).append(qid)
                if item not in v136:
                    fails.append(f"{qid}: lineage entry {item!r} is not a v{C.V1_CURRENT} question id")

    # Disposition coverage: every v1.3.6 question id lands in at least one v2 question
    v2_qids = set(cur["questions"])
    for qid in v136:
        if qid not in all_lineage and qid not in v2_qids:
            fails.append(f"v{C.V1_CURRENT} question {qid} appears in no v2 lineage (disposition coverage)")
    return fails


def dispositions(root: Path, lenses) -> list:
    """Rows for the MIGRATION.md mapping: (v1 id, v1 title, disposition, [(v2 id, v2 title), ...])."""
    v1 = load_v1(root)
    titles = v1_question_titles(v1)
    by_id = {}
    for lens in lenses:
        for q in lens.questions:
            if isinstance(q.get("id"), str):
                by_id[q["id"]] = q
    rows = []
    for v1id, title in titles.items():
        targets = [qid for qid, q in by_id.items() if v1id in (q.get("lineage") or [])]
        if v1id in by_id and v1id not in targets:
            targets.insert(0, v1id)
        targets = sorted(set(targets), key=lambda x: (x != v1id, _order_key(by_id, lenses, x)))
        if v1id in by_id:
            disp = "keep" if len(targets) == 1 else "keep (part moved)"
        elif len(targets) == 1:
            disp = "merge"
        elif len(targets) > 1:
            disp = "split"
        else:
            disp = "unmapped"
        rows.append((v1id, title, disp, [(t, " ".join(str(by_id[t].get("title", "")).split())) for t in targets]))
    return rows


def _order_key(by_id, lenses, qid):
    for li, lens in enumerate(lenses):
        for qi, q in enumerate(lens.questions):
            if q.get("id") == qid:
                return (li, qi)
    return (99, 0)
